name: Deploy to docker hub

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set current date as env variable
        run: echo "::set-env name=NOW::$(date +'%Y-%m-%dT%H:%M:%S')"
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.repository.name }}:${{ env.NOW }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}